### ISSUE TITLE
BUG (KRATOS): There is no input field for user to insert verification code and and to submit it

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3112] opened 2022-12-14 15:56 UTC
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/identity/registration
2. Fill up all required field and use email to which you have access
3. Press "Sign up" button: 
  - user is redirected to https://acc.alkem.io/identity/registration/success.
  - user receive email with code - but there is no place, where he could put it on Alkemio registration/success page
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e7bcc7a9-cc69-44dd-9a9e-18d1e5cdfbba)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/03930441-619f-49e3-9aab-d1771e138e00)

**Expected behavior**
Code input field is available on registrations/success page
Submit button is available on registrations/success page

**Comment by valentinyanakiev** [comment] 2022-12-19 09:43
We take this 'as is' in the current release. If Kratos guys proceed with our idea / we decide to implement it - we take it up separately.

**Comment by techsmyth** [comment] 2024-02-23 10:28
Duplicate of 3795

**Closed by techsmyth** 2024-02-23 10:28 UTC
Labels: bug, client
