### ISSUE TITLE
BUG: Infinite loading when trying to upload image into a markdown editor when we are in an InnovationHub

### ISSUE THREAD

**Issue by ccanos** [alkem-io/client-web#4743] opened 2023-09-11 15:09 UTC
**Describe the bug**
Cant upload an image into a markdown editor, the dialog leaves the clip icon loading forever.
Only happens on markdown editors inside an Innovation Hub.

**To Reproduce**

1. Go to an innovation hub
2. Edit a text for example a card description
3. Click on insert image
4. See error the dialog has a loading animation and doesn't allow you to upload a file

**Expected behavior**
Users should be able to upload images inside markdown editor

**Dev notes**
Possibly a StorageBuckets issue

**Screenshots**
PENDING

**Comment by techsmyth** [comment] 2023-09-19 16:28
@ccanos this is likely a client issue, as there is a request being made that gets the right storage bucket

**Comment by ccanos** [comment] 2023-10-05 16:17
@techsmyth @Comoque1 I cannot reproduce it anymore in dev

**Comment by techsmyth** [comment] 2023-10-05 16:36
@ccanos it may well be that this has been fixed with having a storage bucket per profile...

**Comment by Comoque1** [comment] 2023-10-06 07:38
The issue is still reproducible on DEV and ACC env, for existing innovation hubs. 
When you create a new one, it cannot be reproduced.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUFQQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10ce0f3f8a65668ad9c5572a7ac2b351e7246e88/image.png)

**Closed** 2023-10-10 12:15 UTC
Labels: bug, client, bug squash
