### ISSUE TITLE
BUG: limits on description on innovation pack

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4312] opened 2023-06-29 13:04 UTC
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/f7c7a3f8-9c2f-415d-8916-b5789b30b708)

**To Reproduce**

1. Go to https://alkem.io/admin/innovation-hubs/love-alliance

**Expected behavior**
Character limit on description to be 2,000 characters.

**Comment by Comoque1** [comment] 2023-08-09 08:09
The limit of the description is increased, but we still hit the case, where the user cannot save the changes even, the input field counter is not displaying 2000 chars.

The issues are related: [BUG: Discussion MD, doesn't allow the specified max limit when used new lines, MD visualizers, etc](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/3758) #3758 

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/40d9204c-cf1e-4f1c-84bd-3447048139b8)

@techsmyth, if you accept the current behavior, we can close it, but the issue is generally experienced in many places.

**Closed** 2023-08-11 09:18 UTC
Labels: bug, client, User High Priority, production
