### ISSUE TITLE
BUG: Spike - Login redirect remembering page is not letting me use the application!

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2524] opened 2022-08-30 06:56 UTC
**Describe the bug**
I am being continually redirected to the login page, even after a successful login!

**To Reproduce**
1. Log in to https://acc.alkem.io. Do **NOT** log out.
2. Log in to https://alkem.io.
3. Log out of https://alkem.io.

You will see that you have two cookies `ory_kratos_session`, one for alkem.io and one for .alkem.io domain. The .alkem.io one bugs the logout on alkem.io.

The expected behavior is to have acc.alkem.io as domain of the `ory_kratos_session` on acceptance so the two cookies do not clash.

Behavior seen:
- Signed out
- Click to signin, enter creentials, see success URL
- get brought to signin page again

**Expected behavior**
Redirect to sign in page should only happen when a user tries to access a resource that requires being signed in

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/4bd3dc4c-f794-40cf-a7d1-747879362508)

**Comment by valentinyanakiev** [comment] 2022-09-15 14:09
The issue was caused by experimentation on my side for the settings regarding FFE / Demo Onto Production features on Acceptance.
It has zero impact on users that don't have active session on acceptance, so 0 severity for normal production users.

Fixed by re-installing kratos with normal configuration for acceptance.

**Closed** 2022-09-15 14:21 UTC
Labels: bug, client
