### ISSUE TITLE
BUG: Innovation hub (custom homepage): image button in markdown box not working

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4692] opened 2023-09-05 08:21 UTC
**Describe the bug**
When editing the description of the inclusive innovations custom homepage (https://inclusive-innovations.alkem.io/home), the image button doesn't work correctly. When I click it, it opens the dialog but it keeps loading like this:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWxvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--454143b51d65ce5a7ea00f42520cbf86cc2fa5a8/image.png)

Same thing happens when I click on the image button in the Bulgarian Spaces innovation hub settings.

**To Reproduce**

1. Go to admin settings, inclusive innovations innovation hub
2. Click on add image button in description field

**Comment by techsmyth** [comment] 2023-09-24 13:30
Duplicate of #4743

**Closed by techsmyth** 2023-09-24 13:30 UTC
Labels: bug, client
