### ISSUE TITLE
BUG: Validation is not displayed on client for tagline of an entity

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2788] opened 2022-10-21 11:43 UTC
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/admin/hubs/hub-release-31-08-2022/challenges/chall-release-31-08-2022/opportunities/opp-release-31-08-2022/profile
2. On tagline field set the following text: `opportunity-release-31-08-2022 opportunity-release-31-08-2022 opportunity-release-31-08-2022 opportunity-release-31-08-2022 opportunity-release-31-08-2022 opportunity-release-31-08-2022 opportunity-release-31-08-2022 opportunity-release-31-08-2022 opportunity-release-31-08-2022`
3. Open browser dev tool and save the change - error is thrown in the request response, but not displayed on the client
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8cb65a6b-169c-4210-a72d-74efa15106ac)

**Expected behavior**
TBD

**Comment by techsmyth** [comment] 2022-10-24 19:54
duplicate of client-2211

**Closed by techsmyth** 2022-10-24 19:54 UTC
Labels: bug, client
