### ISSUE TITLE
BUG: Post description image is not displayed

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4761] opened 2023-09-19 09:07 UTC
**Describe the bug**
Simone has created some time ago a post with image in the description. Ate some point the image was not visible.
The request returns to images: 
```
"description":"![](https://media.licdn.com/dms/image/D4E10AQHKgCRsfnZ9Bg/image-shrink_1280/0/1687251365794?e=1689253200\&v=beta\&t=yBN5r90WHjYJaadmCJ9_DfB9PAxU2qkVzqR04lw-QKE)![Voorbeeld van afbeelding](https://media.licdn.com/dms/image/D4E10AQHKgCRsfnZ9Bg/image-shrink_800/0/1687251365794?e=1694509200\&v=beta\&t=eARa3NMoi7Uysed2q2iyeBGz8iBcpk1k8Xr7n24ynEM) " 
```
but they URLs are failing to load for me.

**To Reproduce**

1. Go to https://inclusive-innovations.alkem.io/visimp/collaboration/eengeslaagdeworksh-7991 - image is not displayed
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWV4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cddd42a02d48f0bad1c0035a7de6a163806a7dd1/image.png)

**Expected behavior**
Images are displayed.

**Comment by hero101** [comment] 2023-09-25 13:30
Am I missing something? Is it not visible only while editing or in general? It could have been not available on that server at the moment.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEhSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--28df6ce3a37d3adfe773895c09b1a9983ebd471c/image.png)

**Comment by techsmyth** [comment] 2023-10-23 10:26
A duplicate of 1049 - see the URL that is being linked to: this is a linked in url

**Comment by techsmyth** [comment] 2023-10-23 10:28
Closing as not much we can do.

**Closed by techsmyth** 2023-10-23 10:28 UTC
Labels: bug, client, production
