### ISSUE TITLE
BUG: save contribution fails first time

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#5062] opened 2023-10-30 13:00 UTC
**Describe the bug**
When the save button is not visible in a contribution, but you scroll down to click it: it doesn't save

**To Reproduce**

1. Update a contribution via its settings
2. Scroll down to find and click the save button
3. It is not saved
4. Scroll down again to find and click the save button
5. It is saved

**Expected behavior**
Save the first time

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae34146b2e0a8c08e33fd815842cadcd7431d022/image.png)

**Comment by techsmyth** [comment] 2023-10-30 14:59
@ccanos same issue as the one you are looking at now?

**Comment by techsmyth** [comment] 2023-11-17 09:49
Duplicate of #5052

**Closed by techsmyth** 2023-11-17 09:49 UTC
Labels: bug, client, User High Priority
