### ISSUE TITLE
BUG: Application form values rejected with non-friendly error message

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2145] opened 2022-06-07 10:26 UTC
**Describe the bug**
User completes the application form with a long rational for joining. It is rejected as validation fails:

===
When filling in to join a community, I had provided an extended reason... which resulted in a technical message: ER_DATA_TOO_LONG: Data too long for column 'value' at row 1. As a developer, I can understand that understand what I have to do, but it's not very user-friendly ;-) And maybe the UI could display the max (and possibly still available characters) (á la Twitter)?
====

**Expected behavior**
Client side validation regarding allowed length applied to the fields on a user application form. 
TBD - Length of input allowed displayed??

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/123f0655-1336-484b-9369-7caad7d4e1cb)

**Comment by Comoque1** [comment] 2022-06-21 08:59
The issue is still reproducible. Now there is no message alert shown in the left bottom corner.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/04df2487-ec87-4c3c-affc-6f415a4d1c2e).

Moving to backlog.

**Comment by alstojanovic** [comment] 2022-06-27 08:10
@techsmyth Fix is prepared, just need to figure the max length restriction for the field. (Current is 255, fix is for 512 but we can change to anything else)

**Comment by techsmyth** [comment] 2022-06-27 10:10
I would think the question text field length of 512 is fine. 128 would just be too short I think for someone to give a detailed rational.

**Comment by Comoque1** [comment] 2022-06-28 13:49
Looks good on DEV env now.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e532c980-8e51-43c9-8edf-1636cd90be90)

**Closed by Comoque1** 2022-06-28 13:49 UTC
Labels: bug, client
