### ISSUE TITLE
BUG: Links wrongly displayed on org profile

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6967] opened 2024-10-02 07:55 UTC
**Describe the bug**
The references on an organization profile are either not displayed or the link is displayed instead of the title

**To Reproduce**

1. Compare the org profile settings of an organization with references
2. with the bio on the org profile 

**Expected behavior**
Links to be shown in the same way references are displayed on other places? On user profiles they are displayed as references: https://alkem.io/user/simone-rietmeijer-3706

**Examples**
https://alkem.io/organization/dsih links displayed as links
https://alkem.io/organization/alkemio-foundation links not displayed

**Comment by SimoneZaza** [comment] 2024-10-17 14:32
duplicate of #6961

**Closed by SimoneZaza** 2024-10-17 14:32 UTC
Labels: bug, client, production
