### ISSUE TITLE
BUG: Challenge canvas cannot be checkedin if lifecycle state of challenge was changed upfront

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1851] opened 2022-03-11 11:34 UTC
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/111/challenges/5667/canvases
2. Create new challenge
3. Change the lifecycle state of the challenge
4. Navigate to Challenge / Canvases
5. Create a canvas
6. Edit the canvas
7. Save and stop editing the canvas - error: `"message": "Unable to update state: provided event (CHECKOUT) not in valid set of next events: CHECKIN",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f20fe636-ec24-4d0f-86a0-9690fbe2c16f)

**Expected behavior**
According to the steps above, a canvas can be checked in

**Comment by techsmyth** [comment] 2022-06-20 06:10
Duplicate of client -1779

**Closed by techsmyth** 2022-06-20 06:10 UTC
Labels: bug, client
