### ISSUE TITLE
BUG: Some of the existing VCs lost "Update Knowledge" section

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7081] opened 2024-10-21 13:55 UTC
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/vc/v-p-ec2db2b3-ef3f-452c-bd/settings/settings
2. This is a VC that has been created before external VC creation flow
3. When navigate to its Settings / Settings the "Update Knowledge" section is missing
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0JlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--128242009a37d93c29dee9d8d78f952be2febf53/image.png" alt="image.png" />

**Expected behavior**
Update knowledge section is available for VC based on Alkemio BoK

**Comment by valentinyanakiev** [comment] 2024-10-23 08:05
Closing, added a story to review those VCs - https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/alkemio/1448. Works as intended, based on the data.

**Closed by valentinyanakiev** 2024-10-23 08:05 UTC
Labels: bug, client
