### ISSUE TITLE
BUG (AHT): When adding member users, wrong results are displayed

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#4600] opened 2023-08-22 10:41 UTC
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/admin/spaces/vite-space/challenges/vite-challenge-1844/community
2. Click on 'ADD' button for members
3. Type in search "Carlos"
4. Add the first presented option - error is thrown
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGNtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2db3409996d7b28256a1ff1f0ce8b7a2c4e8adf7/image.png)
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGdtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e5d8364ff10566392ff704149363b0da71f8444d/image.png)

**Expected behavior**
Users, that are not member of perent are not presented in the search results.

**Comment by Comoque1** [comment] 2023-08-22 12:08
Cannot reproduce this issue

**Comment by SimoneZaza** [comment] 2024-01-26 15:16
@Comoque1 Can I close this one (since you couldn't reproduce this back in August already)? :-)

**Closed** 2024-02-08 08:19 UTC
Labels: bug, client
