### ISSUE TITLE
BUG: Updating imported non default innovation flows details cannot be performed

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6924] opened 2024-09-20 07:07 UTC
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/evgeniadminsspace/challenges/packsub
2. Or
3. Create custom innovation flow in a space
4. Set it as default for subspace creation
5. Create a subspace
6. On the subspace open "Innovation flow settings"
7. Click on "pen" icon to edit the innovation flow template
<img width="1526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVB0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c357f5f4e2fe53e2b7ecdc803b4050ab633cf92/image.png" alt="image.png" />

8. Make a change and save it: nothing happens
<img width="1651" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJ0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60abfb68f7c029570c856ef610c95a435252652a/image.png" alt="image.png" />

**Expected behavior**
Changes can be applied.

**Comment by SimoneZaza** [comment] 2024-09-20 13:14
I can't reproduce this in production..? But we might remove that title and description all together, so I'm moving this to the icebox for now

**Closed** 2024-11-12 14:56 UTC
Labels: bug, client
