### ISSUE TITLE
BUG: authorDetails failing due to second userID requested

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1708] opened 2022-01-31 07:57 UTC
**Describe the bug**
Errors on requests for authorDetails

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/b162780c-f918-437b-b23f-950ea73edee3)

Note that a second empty string is being sent up.

**To Reproduce**

1. Click on a hub
2. Look at graphql explorer results

**Expected behavior**
No discussions without the createdBy field set on any of the environments: test, demo, dev, acc. If any fields are empty on the above environments then assign the createdBy to be the UUID from evgeni.
Server to throw an error if it cannot retrieve the createdBy field

**Comment by techsmyth** [comment] 2022-01-31 12:23
On Hub:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/207dd670-e96c-4bf9-8e54-a88e6d0df041)

**Comment by hero101** [comment] 2022-01-31 15:55
Not reproducible.
It may be due to corrupted data - the code below can reproduce the result if the createdBy fields is empty.
```ts
const senders = uniq([...discussions.map(d => d.createdBy)]);
const { getAuthor, loading: loadingAuthors } = useAuthorsDetails(senders);
```
Please point to an environment where the problem is reproducible.

**Comment by techsmyth** [comment] 2022-01-31 17:05
is it not better then to have the cliet do some filtering before requesting the list of authors? Or should the server filter out / ignore empty user IDs? the latter seems wrong to me...

**Comment by hero101** [comment] 2022-02-17 08:40
@valentinyanakiev 
Demo env
```sql
update discussion set createdBy = '4bc90e11-b7e1-4061-8efb-11f282047c65'
where createdBy is NULL or LENGTH(createdBy) = 0;
```
Acc env
```sql
update discussion set createdBy = '0671c529-e101-4536-a656-fa8d927af375'
where createdBy is NULL or LENGTH(createdBy) = 0;
```

**Comment by valentinyanakiev** [comment] 2022-02-18 13:23
Scripts are executed. Fixed on demo / acc. Dev has been re-created after ecoverse -> hub migration.

**Comment by valentinyanakiev** [comment] 2022-02-18 13:24
Code makes sense, approved and left Evgeni to check functionally.

**Closed** 2022-02-21 16:09 UTC
Labels: bug, client
