### ISSUE TITLE
BUG: Clicking on logo at bottom to show about page does stay at bottom

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1053] opened 2021-08-27 13:48 UTC
**Describe the bug**

**To Reproduce**
- [ ] Navigate to "https://acc.alkem.io/"
- [ ] Scroll to bottom an click on "Alkemio" logo
- [ ] User is redirected to "https://acc.alkem.io/**about**"
- [ ] Blank page is displayed, as the scrollbar is in the middle of the page container
![image](https://user-images.githubusercontent.com/23620658/131264704-2ae8dfe7-2022-468a-b002-76c74613a479.png)

**Expected behavior**
Scroll to the top of the page it navigates to / restrict the size of the shown page.
There should not be scroll bars at the bottom. 
Edit the text to not refer to CherryTwist.

**Comment by atstojanov** [comment] 2021-08-29 20:30
The button is only visible when the page is scrolled to the bottom. As normal behavior the button should be visible shortly after the scrolling has begun. The button should be floating over the content (FAB). If implemented to be checked if the button and the notification area don't have collisions.

**Comment by Comoque1** [comment] 2021-08-29 20:36
I believe, the issue mention by Neil is that, when user is redirected to "About" page, after clicking "Logo", the scroller is not moved to top and user see a blank page.
![image](https://user-images.githubusercontent.com/23620658/131264626-60be7f60-47bd-4253-b088-01c75425b5b8.png)

**Comment by Comoque1** [comment] 2021-08-29 20:41
Updated repro steps.

**Comment by techsmyth** [comment] 2021-08-31 15:41
Also noticed today that clicking on a challenge from an ecoverse page has a similar issue - related?

**Comment by Comoque1** [comment] 2021-09-02 06:02
Tested on DEV env.
The issue is still reproducible.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f7476156-33f2-4bfd-976a-e701dfe10509)

Moving to backlog.

**Comment by atstojanov** [comment] 2021-09-02 06:12
the version on dev is not the correct one. The "elipse" on the About page has been removed with the scroll fix.

**Comment by Comoque1** [comment] 2021-09-02 06:15
The PR branch is merged to DEV.
Looks like, we have mergining issues, as I don't see the fix for one more item on DEV env.

**Comment by atstojanov** [comment] 2021-09-02 06:17
The merge is OK. Check what is deployed on dev environment.

**Comment by atstojanov** [comment] 2021-09-02 06:19
Since two PRs.
![image](https://user-images.githubusercontent.com/3524687/131792244-2452372c-0d40-4bc2-b0a9-b8e188a17514.png)

**Comment by Comoque1** [comment] 2021-09-02 08:56
Tested on Test env.
After the implementation of [this changes](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1073), the issue is not reproducible.

The following issues are resolved:
 - [x] Clicking on "Alkemio" icon on footer, redirects to about page on top
 - [x] Clicking on "Explore" button on a "Challenge", redirects to challenge page and scrolls to top
 - [x] "Move to top" button is not part of the footer and is available immediately after scrolling down a bit

Nice set of fixes!!
Closing the issue.

**Closed by Comoque1** 2021-09-02 08:56 UTC
Labels: bug, client
