### ISSUE TITLE
Fix the footer of innovation flow settings dialog

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6094] opened 2024-04-30 11:38 UTC
## Description

As an Admin, I want to have the footer of "Innovation flow settings" dialog fixed, so that I can easily move around the states, when there are many callouts under the same state

## Acceptance criteria

- [ ] TBD

## Additional Context

Screen shots / UX designs / data that are relevant.
<img width="970" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGVqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31a25c68cd9054b4140338cf022e2f17a6a54275/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by SimoneZaza** [comment] 2024-05-30 14:45
Duplicate of #6169

**Closed by SimoneZaza** 2024-05-30 14:45 UTC
Labels: user story, client
