### ISSUE TITLE
Embedded videos not visible on dashboard

### ISSUE THREAD

**Issue by hoyterutteman** [alkem-io/client-web#2099] opened 2022-05-16 13:40 UTC
**Describe the bug**
When embedding a video in an update, the video does not show in the dashboard. It does work in the community tab (though quite narrow)

**To Reproduce**
1. Go to a Challenge/Hub that you're admin of
2. Click on 'Settings / Communications'
3.Write an update containing an embedded video, e.g. : 
```
<iframe src="https://player.vimeo.com/video/708623032?h=31b24edeec" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
<p><a href="https://vimeo.com/708623032">How to use Alkemio</a> from <a href="https://vimeo.com/alkemio">Neil Smyth</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```
4. Post update
5. Go to dashboard, see error

**Expected behavior**
You'd expect the video to be visible in the dashboard view (and to be sized appropriately)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/bfe60fdd-8188-4875-a6bb-5994b85219d8) 

![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/be5741e9-f9b5-47f0-abc6-33decea19bef)

**Comment by techsmyth** [comment] 2022-05-25 18:06
Duplicate of #2095

**Closed by techsmyth** 2022-05-25 18:06 UTC
Labels: bug, client
