### ISSUE TITLE
BUG: Challenge "impact" and "vision" are not displayed

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#847] opened 2021-07-16 11:41 UTC
**Describe the bug**
Challenge "impact" and "vision" are not displayed.

**To Reproduce**

1. Authenticate with GlobalAdmin
2. Navigate to http://localhost:3000/admin/ecoverses/un_sdgs/challenges/ch1/edit - there is available content for `impact` and `vision` entities
3. Navigate to http://localhost:3000/un_sdgs/challenges/ch1 - content for `impact` and `vision` entities is not available
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d7ff6fc5-6f94-4614-b7ca-fe4162dba01b)

**Expected behavior**
Content for `impact` and `vision` entities is available on Challenge page if it is configured

**Comment by techsmyth** [comment] 2021-07-19 06:52
Duplicate of #782

**Closed by techsmyth** 2021-07-19 06:52 UTC
Labels: bug, client
