### ISSUE TITLE
German translations saying "CVC Code"

### ISSUE THREAD

**Issue by me-andre** [alkem-io/client-web#5536] opened 2024-02-12 08:42 UTC
<img width="1268" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34215392b0cd25a910624523f42f8565d21c50ba/Screenshot%202024-02-12%20at%2009.40.33.png" alt="Screenshot 2024-02-12 at 09.40.33.png" />
<img width="826" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHRMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cb5d80c53cdab45115d1352c937ffe74cb4de08/Screenshot%202024-02-12%20at%2009.39.15.png" alt="Screenshot 2024-02-12 at 09.39.15.png" />

**Comment by Comoque1** [comment] 2024-07-12 13:36
The issue is still reproducible on dev env.
<img width="1365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddcbdefb9d602e7fad19e74af0b9f4f4f7baa4f4/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment] 2024-07-12 13:48
That's weird, I've changed this in Crowdin a month ago... <img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFRXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--569e2ab3709a3b11c90c04dd6493482902d11fc7/image.png" alt="image.png" />

**Comment by hero101** [comment] 2024-09-09 06:57
#5198

**Comment by SimoneZaza** [comment] 2024-09-19 16:06
@Comoque1 Since #5198 is closed, I assume this will also be fixed after the next release, can you check & close?

**Comment by Comoque1** [comment] 2024-09-20 15:10
The issue is still reproducible on DEV env: <img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenJ2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5ef8eedf633756802178d30c49979e5dcda8eb3/image.png" alt="image.png" />


On PROD is not reproducible, as the search is configured.

**Comment by SimoneZaza** [comment] 2024-09-23 08:07
Thanks for checking, if it's not reproducible on prod, then I'm closing it.

**Closed by SimoneZaza** 2024-09-23 08:07 UTC
Labels: Product Team
