### ISSUE TITLE
BUG: Banner for cards cropped on card

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#2278] opened 2022-06-30 13:09 UTC
**Describe the bug**
The banner for cards is cropped in the actual card. With this image it is extra clear since the icon is actually centered in the blue overlay:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/2fae3e61-aa5f-4eb3-8f3f-8eeccb1d20f4)

Detail:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/36516ace-6173-419f-93d6-2c25a6f90ff3)

In the settings it is displayed correctly:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/da74bb59-8eb3-44df-9b59-36e3ec3d6c40)

**To Reproduce**
Go to [https://alkem.io/challengecentric/challenges/contribute/dashboard](url) , here it's most visible because of the type of visuals.

**Expected behavior**
It would be nice if the card shows the entire image, not being cropped.

**Comment by Comoque1** [comment] 2022-08-25 11:34
The issue is not resolved. Tested on [ACC](https://acc.alkem.io/hub-release-24-08-2022/dashboard).
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a18cdce9-3cf2-4bc4-b0db-c8e22e872fd7)
Moving to backlog

**Closed** 2023-05-03 13:56 UTC
Labels: bug, client
